remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Jorge Alejandro Bautista
description: Mechatronics engineer with experience implementing the data analysis cycle in R programming projects. 
Inspired by the power of data in business decision-making. 
Looking for a long-term career in data science.
show_downloads: false
